RANGER-4178:NoClassDefFoundError: org/apache/hadoop/hive/ql/exec/vector/ColumnVector
Signed-off-by: Ramesh Mani <rmani@apache.org>
(cherry picked from commit d8dab9f65eb553fd9421b0f6d3cd5f8b96b15948)