RANGER-3482: fix for Kafka plugin initialization failure - NoClassDefFoundError htrace
(cherry picked from commit d73ea981673bc5f5b20d191022695094ec3f47b2)